import { WorkspaceRole } from "@prisma/client";
import { Permission } from "./types";

export const ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  OWNER: [
    "workspace:delete",
    "workspace:transfer",
    "workspace:update",
    "member:manage",
    "member:change_role",
    "invite:manage",
    "project:create",
    "project:update",
    "project:view",
    "task:create",
    "task:update",
    "task:delete",
    "task:view",
    "file:upload",
    "file:delete",
    "file:view",
    "note:create",
    "note:update",
    "note:delete",
    "note:view",
    "chat:send",
    "chat:view",
    "analytics:view",
  ],
  ADMIN: [
    "workspace:update",
    "member:manage",
    "invite:manage",
    "project:create",
    "project:update",
    "project:view",
    "task:create",
    "task:update",
    "task:delete",
    "task:view",
    "file:upload",
    "file:delete",
    "file:view",
    "note:create",
    "note:update",
    "note:delete",
    "note:view",
    "chat:send",
    "chat:view",
    "analytics:view",
  ],
  MEMBER: [
    "project:create",
    "project:view",
    "task:create",
    "task:update",
    "task:view",
    "file:upload",
    "file:view",
    "note:create",
    "note:update",
    "note:view",
    "chat:send",
    "chat:view",
  ],
  GUEST: [
    "project:view",
    "task:view",
    "file:view",
    "note:view",
    "chat:view",
  ],
};
